### ISSUE TITLE
Make the suggested utterances grammatically correct

### ISSUE THREAD

**Issue by ChanceNCounter** [OpenVoiceOS/skill-ovos-homescreen#4]
"Ask me, Tell me a joke" looks weird. 'Tell me a joke' isn't a question. We should try to pair strings.

"Say, Tell me a joke"  
"Ask me, How is the weather?"

**Comment by NeonDaniel** [comment]
I would propose moving all string building to the skill providing the examples. This would let devs opt to include a wake word in examples or not too (also probably easier for translation?)

**Comment by ChanceNCounter** [comment]
Might be easier for translation. The wake word part, I dunno. It occurred to me yesterday or the day before that the "ask me" vs. "say" thing can be handled with f-strings, if the examples gain syntax, but that also puts something on skill devs that wasn't before.

**Comment by NeonDaniel** [comment]
It puts it on the dev who writes the skill that provides examples, but I think that's where it belongs since it lets them put exactly what they want on the home screen

**Comment by JarbasAl** [comment]
closing this one, to be solved together with https://github.com/OpenVoiceOS/skill-ovos-homescreen/issues/104
