### ISSUE TITLE
Event `ovos.homescreen.displayed` after homescreen is fully loaded 

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/skill-ovos-homescreen#82]
We got a commit [here](https://github.com/OpenVoiceOS/skill-ovos-homescreen/commit/f8cf01891fe60d8f2b9b638fa69050e04aa861b5) that never got it to a PR, but is necessary if a skill waits for the homescreen to be completely loaded (eg. widgets update). Could we get this in?

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/65
